### ISSUE TITLE
Github CI

### ISSUE THREAD

**Issue by pozitronik** [cusodede/yii2-queue-mailer#2]
Впилить прогон тестов при PR.
Пример можно зазырить [тут](https://github.com/cusodede/yii2-default-controller/blob/master/.github/workflows/ci_with_postgresql.yml).

**Comment by s1lver** [comment]
С тех пор я, слегка, улучшил этот способ. Теперь надо меньше всего делать чтобы работало везде одинаково в Docker

**Comment by pozitronik** [comment]
> С тех пор я, слегка, улучшил этот способ. Теперь надо меньше всего делать чтобы работало везде одинаково в Docker

Ну так делай PR.
